-- v063: CRM Prospect Staging DB Schema Proposal (documentation-only, no execution by default)
-- Safe scope: prepares staging tables for prospect pipeline without using clients/contracts/payment_schedule.

CREATE TABLE IF NOT EXISTS lead_sources (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_code VARCHAR(40) NOT NULL,
  source_ref VARCHAR(120) NULL,
  environment ENUM('staging','production') NOT NULL DEFAULT 'staging',
  is_test BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  raw_payload_json JSON NULL,
  normalized_payload_json JSON NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lead_sources_actor_user FOREIGN KEY (actor_user_id) REFERENCES crm_users(id),
  UNIQUE KEY uq_lead_sources_code_ref_env (source_code, source_ref, environment)
);

CREATE TABLE IF NOT EXISTS prospects (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_ref VARCHAR(120) NULL,
  source_ref VARCHAR(120) NULL,
  source ENUM('whatsapp_txt','manual','demo','import') NOT NULL DEFAULT 'demo',
  environment ENUM('staging','production') NOT NULL DEFAULT 'staging',
  is_test BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  lead_source_id BIGINT UNSIGNED NULL,
  seller_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  name VARCHAR(160) NOT NULL,
  phone_original VARCHAR(60) NULL,
  phone_normalized VARCHAR(30) NULL,
  property_interest VARCHAR(160) NULL,
  status VARCHAR(60) NOT NULL DEFAULT 'new',
  intention_level VARCHAR(60) NULL,
  next_action VARCHAR(255) NULL,
  raw_payload_json JSON NULL,
  normalized_payload_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_prospects_lead_source FOREIGN KEY (lead_source_id) REFERENCES lead_sources(id),
  CONSTRAINT fk_prospects_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
  CONSTRAINT fk_prospects_actor_user FOREIGN KEY (actor_user_id) REFERENCES crm_users(id),
  KEY idx_prospects_phone_normalized (phone_normalized),
  KEY idx_prospects_status (status)
);

CREATE TABLE IF NOT EXISTS whatsapp_conversations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_ref VARCHAR(120) NULL,
  source_ref VARCHAR(120) NULL,
  prospect_id BIGINT UNSIGNED NOT NULL,
  seller_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  source ENUM('whatsapp_txt','manual','demo','import') NOT NULL DEFAULT 'whatsapp_txt',
  environment ENUM('staging','production') NOT NULL DEFAULT 'staging',
  is_test BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  phone_original VARCHAR(60) NULL,
  phone_normalized VARCHAR(30) NULL,
  raw_payload_json JSON NULL,
  normalized_payload_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_whatsapp_conversations_prospect FOREIGN KEY (prospect_id) REFERENCES prospects(id),
  CONSTRAINT fk_whatsapp_conversations_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
  CONSTRAINT fk_whatsapp_conversations_actor_user FOREIGN KEY (actor_user_id) REFERENCES crm_users(id),
  KEY idx_whatsapp_conversations_phone_normalized (phone_normalized)
);

CREATE TABLE IF NOT EXISTS whatsapp_analyses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_ref VARCHAR(120) NULL,
  source_ref VARCHAR(120) NULL,
  prospect_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  seller_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  source ENUM('whatsapp_txt','manual','demo','import') NOT NULL DEFAULT 'whatsapp_txt',
  environment ENUM('staging','production') NOT NULL DEFAULT 'staging',
  is_test BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  intention_level VARCHAR(60) NULL,
  next_action VARCHAR(255) NULL,
  raw_payload_json JSON NULL,
  normalized_payload_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_whatsapp_analyses_prospect FOREIGN KEY (prospect_id) REFERENCES prospects(id),
  CONSTRAINT fk_whatsapp_analyses_conversation FOREIGN KEY (conversation_id) REFERENCES whatsapp_conversations(id),
  CONSTRAINT fk_whatsapp_analyses_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
  CONSTRAINT fk_whatsapp_analyses_actor_user FOREIGN KEY (actor_user_id) REFERENCES crm_users(id)
);

CREATE TABLE IF NOT EXISTS prospect_followups (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_ref VARCHAR(120) NULL,
  source_ref VARCHAR(120) NULL,
  prospect_id BIGINT UNSIGNED NOT NULL,
  seller_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  source ENUM('whatsapp_txt','manual','demo','import') NOT NULL DEFAULT 'manual',
  environment ENUM('staging','production') NOT NULL DEFAULT 'staging',
  is_test BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  status VARCHAR(60) NOT NULL DEFAULT 'pending',
  next_action VARCHAR(255) NULL,
  raw_payload_json JSON NULL,
  normalized_payload_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_prospect_followups_prospect FOREIGN KEY (prospect_id) REFERENCES prospects(id),
  CONSTRAINT fk_prospect_followups_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
  CONSTRAINT fk_prospect_followups_actor_user FOREIGN KEY (actor_user_id) REFERENCES crm_users(id)
);

CREATE TABLE IF NOT EXISTS crm_history_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_ref VARCHAR(120) NULL,
  source_ref VARCHAR(120) NULL,
  prospect_id BIGINT UNSIGNED NULL,
  followup_id BIGINT UNSIGNED NULL,
  conversation_id BIGINT UNSIGNED NULL,
  analysis_id BIGINT UNSIGNED NULL,
  seller_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  source ENUM('whatsapp_txt','manual','demo','import') NOT NULL DEFAULT 'demo',
  environment ENUM('staging','production') NOT NULL DEFAULT 'staging',
  is_test BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  event_type VARCHAR(80) NOT NULL,
  status VARCHAR(60) NULL,
  intention_level VARCHAR(60) NULL,
  next_action VARCHAR(255) NULL,
  raw_payload_json JSON NULL,
  normalized_payload_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_history_events_prospect FOREIGN KEY (prospect_id) REFERENCES prospects(id),
  CONSTRAINT fk_crm_history_events_followup FOREIGN KEY (followup_id) REFERENCES prospect_followups(id),
  CONSTRAINT fk_crm_history_events_conversation FOREIGN KEY (conversation_id) REFERENCES whatsapp_conversations(id),
  CONSTRAINT fk_crm_history_events_analysis FOREIGN KEY (analysis_id) REFERENCES whatsapp_analyses(id),
  CONSTRAINT fk_crm_history_events_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
  CONSTRAINT fk_crm_history_events_actor_user FOREIGN KEY (actor_user_id) REFERENCES crm_users(id)
);
